# Experimental test coins only. Use a NEW, dedicated datadir.
signet=1
xbtcovtest=1
signetchallenge=2102396d38e3ff703be31a2d97317835f4e9645b5ae5ea2d2d1ba406afa7ab185b5fac
signetblocktime=60
dnsseed=0
server=1
[signet]
addnode=node2.paperclippool.xyz:48333
port=48333
rpcport=48332
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
